---
- hosts: dbgroup
  user: root
  become: true

  vars:
    pack_name: httpd
    serv_name: httpd

  tasks:
      - name: Install {{ pack_name }}
        yum: pkg={{ pack_name }} state=installed
      - name: Start {{ serv_name }}
        Service: name={{ serv_name }} state=started
